#!/usr/bin/env bash
desc="Create/update workspace .mtx.prepare.env (Railway, master DB, master public URL)"
nobanner=1
set -e

MTX_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=includes/prepare-env.sh
source "$MTX_ROOT/includes/prepare-env.sh"

PROJECT_ROOT=""
if [ -f "config/org.json" ] || [ -f "config/app.json" ]; then
  PROJECT_ROOT="$(pwd)"
fi
if [ -z "$PROJECT_ROOT" ] && { [ -f "../config/org.json" ] || [ -f "../config/app.json" ]; }; then
  PROJECT_ROOT="$(cd .. && pwd)"
fi
if [ -z "$PROJECT_ROOT" ]; then
  for d in . .. ../project-bridge; do
    { [ -f "${d}/config/org.json" ] || [ -f "${d}/config/app.json" ]; } && PROJECT_ROOT="$(cd "$d" && pwd)" && break
  done
fi
[ -z "$PROJECT_ROOT" ] && PROJECT_ROOT="$(pwd)"

WORKSPACE_ROOT="$(mtx_detect_workspace_root "$PROJECT_ROOT")" || {
  echo "❌ Workspace root not found (missing *.code-workspace in parent chain)." >&2
  exit 1
}
PREPARE_FILE="$(mtx_prepare_file_path "$WORKSPACE_ROOT")"

# Intentionally do NOT read $PROJECT_ROOT/.env here. Per-org .env is for deploy-time / build-time
# secrets in that host; the workspace prepare file is the single place for shared RAILWAY_* ids/tokens.
# Seeding from org .env caused wrong tokens to leak into .mtx.prepare.env when switching cwd between orgs.
# Pre-fill: existing .mtx.prepare.env, then any RAILWAY_* already exported in the parent shell (CI).
if [ -f "$PREPARE_FILE" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$PREPARE_FILE"
  set +a
fi

read_or_keep() {
  local key="$1"
  local label="$2"
  local current cleaned input
  current="$(mtx_trim_inline "${!key:-}")"
  if [ -n "$current" ]; then
    printf -v "$key" '%s' "$current"
    export "$key"
    echo "✅ $key already set"
    return 0
  fi
  if [ ! -t 0 ]; then
    echo "❌ Missing required value in non-interactive mode: $key" >&2
    return 1
  fi
  echo ""
  echo "$label"
  read -r -sp "$key: " input
  echo ""
  cleaned="$(mtx_trim_inline "$input")"
  if [ -z "$cleaned" ]; then
    echo "❌ $key cannot be empty." >&2
    return 1
  fi
  printf -v "$key" '%s' "$cleaned"
  export "$key"
}

# Optional key: empty line keeps existing empty / unset; uses default later.
read_or_keep_optional() {
  local key="$1" label="$2" current input cleaned
  current="$(mtx_trim_inline "${!key:-}")"
  if [ -n "$current" ]; then
    printf -v "$key" '%s' "$current"
    export "$key"
    echo "✅ $key already set"
    return 0
  fi
  if [ ! -t 0 ]; then
    return 0
  fi
  echo ""
  echo "$label"
  read -r -sp "$key (optional, Enter to skip): " input
  echo ""
  cleaned="$(mtx_trim_inline "$input")"
  if [ -n "$cleaned" ]; then
    printf -v "$key" '%s' "$cleaned"
    export "$key"
  else
    unset "$key" 2>/dev/null || true
  fi
}

echo "🧰 MTX prepare"
echo "Workspace root: $WORKSPACE_ROOT"
echo "Prepare file:   $PREPARE_FILE"
echo ""

read_or_keep "RAILWAY_ACCOUNT_TOKEN" "Railway account token (https://railway.app/account/tokens)"
read_or_keep "RAILWAY_WORKSPACE_ID" "Railway workspace ID"
read_or_keep "RAILWAY_PROJECT_ID" "Railway project ID (shared workspace-level deploy target)"
read_or_keep "RAILWAY_PROJECT_TOKEN_STAGING" "Railway project token scoped to staging"
read_or_keep "RAILWAY_PROJECT_TOKEN_PRODUCTION" "Railway project token scoped to production"

echo ""
echo "Platform singletons (one master app DB and public origin for the whole system):"
read_or_keep "MASTER_DATABASE_URL" "Master app DATABASE_URL (Postgres URL for the master org — same for all orgs/operator tools)"
read_or_keep_optional "MASTER_BACKEND_DATABASE_URL" "Optional: master backend DB URL (Enter if app and backend use the same database)"
read_or_keep "MASTER_AUTH_PUBLIC_URL" "Master public origin (e.g. https://your-master.up.railway.app) — used to derive VITE_MASTER_AUTH_URL for all org builds"

# Strip optional if empty for file output
M_BE_LINE=""
if [ -n "${MASTER_BACKEND_DATABASE_URL:-}" ]; then
  M_BE_LINE="MASTER_BACKEND_DATABASE_URL=$MASTER_BACKEND_DATABASE_URL"
fi

tmp="${PREPARE_FILE}.tmp"
{
  echo "# MTX workspace-level deploy credentials, Railway ids/tokens, and platform singletons."
  echo "# Generated by: mtx prepare"
  echo "# Do not commit this file."
  echo "RAILWAY_ACCOUNT_TOKEN=$RAILWAY_ACCOUNT_TOKEN"
  echo "RAILWAY_WORKSPACE_ID=$RAILWAY_WORKSPACE_ID"
  echo "RAILWAY_PROJECT_ID=$RAILWAY_PROJECT_ID"
  echo "RAILWAY_PROJECT_TOKEN_STAGING=$RAILWAY_PROJECT_TOKEN_STAGING"
  echo "RAILWAY_PROJECT_TOKEN_PRODUCTION=$RAILWAY_PROJECT_TOKEN_PRODUCTION"
  echo "MASTER_DATABASE_URL=$MASTER_DATABASE_URL"
  [ -n "$M_BE_LINE" ] && echo "$M_BE_LINE"
  echo "MASTER_AUTH_PUBLIC_URL=$MASTER_AUTH_PUBLIC_URL"
} > "$tmp"
mv "$tmp" "$PREPARE_FILE"
chmod 600 "$PREPARE_FILE" 2>/dev/null || true

echo ""
echo "✅ Prepare file written."
echo "   $PREPARE_FILE"
