#!/usr/bin/env bash
desc="Create/update workspace-level Railway token/id prepare file"
nobanner=1
set -e

MTX_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=includes/prepare-env.sh
source "$MTX_ROOT/includes/prepare-env.sh"

PROJECT_ROOT=""
if [ -f "config/app.json" ]; then
  PROJECT_ROOT="$(pwd)"
fi
if [ -z "$PROJECT_ROOT" ] && [ -f "../config/app.json" ]; then
  PROJECT_ROOT="$(cd .. && pwd)"
fi
if [ -z "$PROJECT_ROOT" ]; then
  for d in . .. ../project-bridge; do
    [ -f "${d}/config/app.json" ] && PROJECT_ROOT="$(cd "$d" && pwd)" && break
  done
fi
[ -z "$PROJECT_ROOT" ] && PROJECT_ROOT="$(pwd)"

WORKSPACE_ROOT="$(mtx_detect_workspace_root "$PROJECT_ROOT")" || {
  echo "❌ Workspace root not found (missing *.code-workspace in parent chain)." >&2
  exit 1
}
PREPARE_FILE="$(mtx_prepare_file_path "$WORKSPACE_ROOT")"
PROJECT_ENV_FILE="$PROJECT_ROOT/.env"

# Load existing values from project .env and existing prepare file, then env vars override.
if [ -f "$PROJECT_ENV_FILE" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$PROJECT_ENV_FILE"
  set +a
fi
if [ -f "$PREPARE_FILE" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$PREPARE_FILE"
  set +a
fi

read_or_keep() {
  local key="$1"
  local label="$2"
  local current cleaned input
  current="$(mtx_trim_inline "${!key:-}")"
  if [ -n "$current" ]; then
    printf -v "$key" '%s' "$current"
    export "$key"
    echo "✅ $key already set"
    return 0
  fi
  if [ ! -t 0 ]; then
    echo "❌ Missing required value in non-interactive mode: $key" >&2
    return 1
  fi
  echo ""
  echo "$label"
  read -r -sp "$key: " input
  echo ""
  cleaned="$(mtx_trim_inline "$input")"
  if [ -z "$cleaned" ]; then
    echo "❌ $key cannot be empty." >&2
    return 1
  fi
  printf -v "$key" '%s' "$cleaned"
  export "$key"
}

echo "🧰 MTX prepare"
echo "Workspace root: $WORKSPACE_ROOT"
echo "Prepare file:   $PREPARE_FILE"
echo ""

read_or_keep "RAILWAY_ACCOUNT_TOKEN" "Railway account token (https://railway.app/account/tokens)"
read_or_keep "RAILWAY_WORKSPACE_ID" "Railway workspace ID"
read_or_keep "RAILWAY_PROJECT_ID" "Railway project ID (shared workspace-level deploy target)"
read_or_keep "RAILWAY_PROJECT_TOKEN_STAGING" "Railway project token scoped to staging"
read_or_keep "RAILWAY_PROJECT_TOKEN_PRODUCTION" "Railway project token scoped to production"

tmp="${PREPARE_FILE}.tmp"
cat > "$tmp" <<EOF
# MTX workspace-level deploy credentials and IDs.
# Generated by: mtx prepare
# Do not commit this file.
RAILWAY_ACCOUNT_TOKEN=$RAILWAY_ACCOUNT_TOKEN
RAILWAY_WORKSPACE_ID=$RAILWAY_WORKSPACE_ID
RAILWAY_PROJECT_ID=$RAILWAY_PROJECT_ID
RAILWAY_PROJECT_TOKEN_STAGING=$RAILWAY_PROJECT_TOKEN_STAGING
RAILWAY_PROJECT_TOKEN_PRODUCTION=$RAILWAY_PROJECT_TOKEN_PRODUCTION
EOF
mv "$tmp" "$PREPARE_FILE"
chmod 600 "$PREPARE_FILE" 2>/dev/null || true

echo ""
echo "✅ Prepare file written."
echo "   $PREPARE_FILE"
