#!/usr/bin/env bash
# Self-contained deploy bundle: unified server dist + npm pack tarballs + deploy manifests.
# Railway runs only: npm install --omit=dev --ignore-scripts (no vendor/, no git fetch of project-bridge).
# Run locally before railway up / mtx deploy (requires sibling project-bridge or PROJECT_BRIDGE_ROOT).
#
# Usage: prepare-railway-artifact.sh [deploy-root]
#
# Produces:
#   targets/server/dist/              — mirrored from project-bridge (server build)
#   targets/client/dist/              — mirrored Vite web app (build:client; required for production static UI)
#   targets/server/npm-packs/*.tgz    — packed @meanwhile-together/* workspaces
#   package.deploy.json + package-lock.deploy.json — full prod deps; Railway npm install materializes node_modules
#   scripts/railway-migrate.mjs        — copied from project-bridge for preDeployCommand
#   .railway-self-contained           — marker for install/build scripts
desc="Assemble Railway self-contained bundle (dist, npm packs, deploy manifests)"
nobanner=1
set -euo pipefail

_script="${BASH_SOURCE[0]:-$0}"
MTX_ROOT="$(cd "$(dirname "$_script")/.." && pwd)"
export MTX_ROOT

if [ -n "${1:-}" ]; then
  ROOT="$(cd "$1" && pwd)"
else
  ROOT="$(pwd)"
fi

PB="${PROJECT_BRIDGE_ROOT:-$ROOT/../project-bridge}"

if [ ! -f "$PB/package.json" ]; then
  echo "prepare-railway-artifact: project-bridge not found at $PB" >&2
  echo "  Set PROJECT_BRIDGE_ROOT or place project-bridge next to this deploy root (../project-bridge)." >&2
  exit 1
fi

if [ "${MTX_SKIP_PAYLOAD_VENDOR:-}" != "1" ] && [ -f "$ROOT/config/server.json" ]; then
  echo "==> prepare-railway-artifact: vendor + build path payloads from config/server.json"
  if [ ! -f "$MTX_ROOT/lib/vendor-payloads-from-config.sh" ]; then
    echo "prepare-railway-artifact: missing $MTX_ROOT/lib/vendor-payloads-from-config.sh" >&2
    exit 1
  fi
  bash "$MTX_ROOT/lib/vendor-payloads-from-config.sh" "$ROOT" || exit 1
fi

echo "==> prepare-railway-artifact: unified server build (deploy config -> project-bridge)"
bash "$MTX_ROOT/project/org-build-server.sh" "$ROOT"

echo "==> prepare-railway-artifact: bundle prisma schemas + migrations for runtime migrate deploy"
(
  cd "$PB"
  DATABASE_PROVIDER=postgresql npx --yes tsx scripts/prepare-prisma-schema.ts
)
rm -rf "$ROOT/prisma"
mkdir -p "$ROOT/prisma"
# project-bridge: prisma/app (multi-file) + prisma/admin (service-admin catalog). Matches scripts/railway-migrate.mjs.
for target in app admin; do
  src_dir="$PB/prisma/$target"
  if [ ! -d "$src_dir" ]; then
    echo "prepare-railway-artifact: missing directory $src_dir — did prepare-prisma-schema.ts run?" >&2
    exit 1
  fi
  shopt -s nullglob
  _prisma_files=( "$src_dir"/*.prisma )
  shopt -u nullglob
  if [ ${#_prisma_files[@]} -eq 0 ]; then
    echo "prepare-railway-artifact: no *.prisma in $src_dir" >&2
    exit 1
  fi

  mkdir -p "$ROOT/prisma/$target"
  rsync -a --delete "$src_dir/migrations/" "$ROOT/prisma/$target/migrations/" 2>/dev/null || true

  for src_prisma in "${_prisma_files[@]}"; do
    base="$(basename "$src_prisma")"
    node - "$src_prisma" "$ROOT/prisma/$target/$base" <<'NODE'
const fs = require('fs');
const [src, dst] = process.argv.slice(2);
let s = fs.readFileSync(src, 'utf8');
s = s.replace(/datasource\s+db\s*\{([^}]*)\}/m, (_m, body) => {
  const scrubbed = body
    .split('\n')
    .filter((line) => !/^\s*url\s*=/.test(line))
    .join('\n')
    .replace(/\s+$/, '');
  return `datasource db {${scrubbed}\n}`;
});
fs.mkdirSync(require('path').dirname(dst), { recursive: true });
fs.writeFileSync(dst, s);
NODE
  done

  if [ "$target" = app ]; then
    cat > "$ROOT/prisma/$target/prisma.config.ts" <<'TS'
// Auto-generated by prepare-railway-artifact.sh. Do not hand-edit in the deploy bundle.
// Prisma 7: app schema is a directory root (schema.prisma + *.schema.prisma fragments). See project-bridge/prisma/app/prisma.config.ts.
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error(
    'DATABASE_URL is required to run Prisma migrate against this bundle. ' +
      'Set it on the service (Railway wires this automatically when a Postgres plugin is attached).',
  );
}

const datasource: { url: string; shadowDatabaseUrl?: string } = { url };
const shadow =
  process.env.DATABASE_SHADOW_URL ??
  process.env.DATABASE_DIRECT_URL ??
  process.env.SHADOW_DATABASE_URL;
if (shadow) datasource.shadowDatabaseUrl = shadow;

export default {
  schema: here,
  migrations: {
    path: path.resolve(here, 'migrations'),
  },
  datasource,
};
TS
  else
    cat > "$ROOT/prisma/$target/prisma.config.ts" <<'TS'
// Auto-generated by prepare-railway-artifact.sh. Do not hand-edit in the deploy bundle.
// Prisma 7 CLI loads this config (same dir as schema.prisma) to wire DATABASE_URL at migrate time.
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error(
    'DATABASE_URL is required to run Prisma migrate against this bundle. ' +
      'Set it on the service (Railway wires this automatically when a Postgres plugin is attached).',
  );
}

const datasource: { url: string; shadowDatabaseUrl?: string } = { url };
const shadow =
  process.env.DATABASE_SHADOW_URL ??
  process.env.DATABASE_DIRECT_URL ??
  process.env.SHADOW_DATABASE_URL;
if (shadow) datasource.shadowDatabaseUrl = shadow;

export default {
  schema: path.resolve(here, 'schema.prisma'),
  migrations: {
    path: path.resolve(here, 'migrations'),
  },
  datasource,
};
TS
  fi
done
mkdir -p "$ROOT/scripts"
cp -a "$PB/scripts/railway-migrate.mjs" "$ROOT/scripts/railway-migrate.mjs"

echo "==> prepare-railway-artifact: generate deploy manifests (npm pack + lockfile)"
bash "$MTX_ROOT/project/generate-railway-deploy-manifest.sh" "$ROOT"

touch "$ROOT/.railway-self-contained"

echo ""
echo "✅ Self-contained bundle ready."
echo "   Deploy: mtx deploy  (swaps config/server.json.railway for upload when path payloads were vendored)"
echo "   Or: railway up --no-gitignore — if server.json.railway exists, copy it over config/server.json first."
echo "   Railway install: npm install only — no project-bridge clone."
echo "   Re-run after config/ or project-bridge dependency changes."
